version: '2'

services:

    #fast-CGI processer manager

    #nginx web app
    server:
        build: ./docker/server
        image: server:0.1
        container_name: server
        networks:
            vmms_network:
                ipv4_address: 172.20.0.4
        ports:
            - '80:80'
            - '443:443'
        volumes:
            #nginx conf
            - ./etc/nginx/conf.d:/etc/nginx/conf.d
            #- ./etc/nginx/snippets:/etc/nginx/snippets
            - ./var/web:/var/www/web
            - ./var/www/certbot:/var/www/certbot
            - ./etc/nginx/letsencrypt/:/etc/letsencrypt/
            - ./etc/httpd/conf.d/web:/etc/httpd/conf.d/web
            #- ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf
            #log    
            #- ./logs/nginx:/var/log/nginx
        restart: always

#volumes:
#  db-data:
#  www:

networks:
  vmms_network:
    ipam:
       config:
           - subnet: 172.20.0.0/16
